[workspace]
workspace.resolver = "2"
members = [
  "totsugeki",
  "totsugeki-display",
  "totsugeki-discord-bot",
  "totsugeki-native-app",
  "dioxus-components",
  "web",
  "tournament-organiser-api",
  "ui",
]
