[workspace]
members = [
  "discord-bot",
  "frontend",
  "totsugeki",
  "tournament-server",
  "tournament-server-request",
]

[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
async-trait = "0.1"
cucumber = "0.13"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
env_logger = "0.9.0"
dotenv = "0.15"
log = "0.4.17"
tournament-server-request = { path = "tournament-server-request" }
reqwest = "0.11.11"

[[test]]
name = "bracket"
harness = false
