# fly.toml app configuration file generated for totsugeki on 2023-10-07T13:30:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "totsugeki"
primary_region = "cdg"

[build]

[env]
  BUILD_PATH_TOURNAMENT_ORGANISER_WEB = "dist"
  DOCKER_BUILD = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
