
# https://github.com/actions-rs/meta/blob/d7602e71e8b4e6054edbeda7732ed0da8fbb8989/recipes/quickstart.md
on: [push, pull_request]

name: CI abandonned experiments

# use matrix strategy to check https://stackoverflow.com/a/65857032
# TODO refactor steps with local actions following https://alejandrocelaya.blog/2022/08/19/how-to-reduce-duplication-in-your-github-actions-workflows/

jobs:
  check:
    name: Check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy: 
      matrix: { 
        dir: [
          'examples/totsugeki-discord-bot',
          'examples/totsugeki-native-app',
          'examples/web',
        ]}
    env:
      API_ADDR: localhost
      API_PORT: 8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            examples/*/target/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # setup
      - name: update system repos
        if: ${{ matrix.dir == 'examples/totsugeki-native-app' }}
        run: sudo apt-get update
      # https://dioxuslabs.com/docs/0.3/guide/en/getting_started/desktop.html#linux
      - name: install dioxus system deps
        if: ${{ matrix.dir == 'examples/totsugeki-native-app' }}
        run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
      - run: mkdir resources # totsugeki-native-app+web
        if: ${{ matrix.dir != 'examples/totsugeki-discord-bot' }}
        working-directory: ${{ matrix.dir }}
      - run: touch resources/tailwind.css
        if: ${{ matrix.dir != 'examples/totsugeki-discord-bot' }}
        working-directory: ${{ matrix.dir }}

      - run: cargo check
        working-directory: ${{ matrix.dir }}
  
  test:
    name: test
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy: 
      matrix: { 
        dir: [
          'examples/totsugeki-discord-bot',
          'examples/totsugeki-native-app',
          'examples/web',
        ]}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            examples/*/target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: update system repos
        if: ${{ matrix.dir == 'examples/totsugeki-native-app' }}
        run: sudo apt-get update
      # https://dioxuslabs.com/docs/0.3/guide/en/getting_started/desktop.html#linux
      - name: install dioxus system deps
        if: ${{ matrix.dir == 'examples/totsugeki-native-app' }}
        run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
      - run: mkdir resources # totsugeki-native-app+web
        if: ${{ matrix.dir != 'examples/totsugeki-discord-bot' }}
        working-directory: ${{ matrix.dir }}
      - run: touch resources/tailwind.css
        if: ${{ matrix.dir != 'examples/totsugeki-discord-bot' }}
        working-directory: ${{ matrix.dir }}

      - run: cargo test
        working-directory: ${{ matrix.dir }}

  lint-rust:
    name: Rustfmt
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy: 
      matrix: { 
        dir: [
          'examples/totsugeki-discord-bot',
          'examples/totsugeki-native-app',
          'examples/web',
        ]}
    env:
      API_ADDR: localhost
      API_PORT: 8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            examples/*/target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
        working-directory: ${{ matrix.dir }}

  clippy:
    name: Clippy
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy: 
      matrix: { 
        dir: [
          'examples/totsugeki-discord-bot',
          'examples/totsugeki-native-app',
          'examples/web',
        ]}
    env:
      API_ADDR: localhost
      API_PORT: 8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            examples/*/target/
            tournament-organiser-web/node_modules
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add clippy
      
      # setup
      - name: update system repos
        if: ${{ matrix.dir == 'examples/totsugeki-native-app' }}
        run: sudo apt-get update
      # https://dioxuslabs.com/docs/0.3/guide/en/getting_started/desktop.html#linux
      - name: install dioxus system deps
        if: ${{ matrix.dir == 'examples/totsugeki-native-app' }}
        run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
      - run: mkdir resources # totsugeki-native-app+web
        if: ${{ matrix.dir != 'examples/totsugeki-discord-bot' }}
        working-directory: ${{ matrix.dir }}
      - run: touch resources/tailwind.css
        if: ${{ matrix.dir != 'examples/totsugeki-discord-bot' }}
        working-directory: ${{ matrix.dir }}

      - run: cargo clippy -- -D warnings
        working-directory: ${{ matrix.dir }}
