# https://github.com/actions-rs/meta/blob/d7602e71e8b4e6054edbeda7732ed0da8fbb8989/recipes/quickstart.md
on: [ push, pull_request ]

name: CI abandonned experiments

# use matrix strategy to check https://stackoverflow.com/a/65857032
# TODO refactor steps with local actions following https://alejandrocelaya.blog/2022/08/19/how-to-reduce-duplication-in-your-github-actions-workflows/

jobs:
  check:
    name: Check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix: {
        dir: [
          'examples/totsugeki-discord-bot',
        ] }
    env:
      API_ADDR: localhost
      API_PORT: 8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            examples/*/target/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo check
        working-directory: ${{ matrix.dir }}
  
  test:
    name: test
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix: {
        dir: [
          'examples/totsugeki-discord-bot',
        ] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            examples/*/target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test
        working-directory: ${{ matrix.dir }}

  lint-rust:
    name: Rustfmt
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix: {
        dir: [
          'examples/totsugeki-discord-bot',
        ] }
    env:
      API_ADDR: localhost
      API_PORT: 8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            examples/*/target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
        working-directory: ${{ matrix.dir }}

  clippy:
    name: Clippy
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix: {
        dir: [
          'examples/totsugeki-discord-bot',
        ] }
    env:
      API_ADDR: localhost
      API_PORT: 8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            examples/*/target/
            tournament-organiser-web/node_modules
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
        working-directory: ${{ matrix.dir }}
