# https://github.com/actions-rs/meta/blob/d7602e71e8b4e6054edbeda7732ed0da8fbb8989/recipes/quickstart.md
on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      API_ADDR: localhost
      API_PORT: 3000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # setup
      - run: sudo apt-get update
      # https://dioxuslabs.com/docs/0.3/guide/en/getting_started/desktop.html#linux
      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
      - run: mkdir totsugeki-native-app/resources
      - run: touch totsugeki-native-app/resources/tailwind.css
      - run: mkdir web/resources
      - run: touch web/resources/tailwind.css

      - run: cargo check
  
  # TODO compile tailwindcss using tailwind cli in CI

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    env:
      API_ADDR: localhost
      API_PORT: 3000
      API_DB_TYPES_IN_TESTS: INMEMORY
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # setup
      - run: sudo apt-get update
      # https://dioxuslabs.com/docs/0.3/guide/en/getting_started/desktop.html#linux
      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
      - run: mkdir totsugeki-native-app/resources
      - run: touch totsugeki-native-app/resources/tailwind.css
      - run: mkdir web/resources
      - run: touch web/resources/tailwind.css

      - run: cargo test -- --include-ignored

  lint-rust:
    name: Rustfmt
    runs-on: ubuntu-latest
    env:
      API_ADDR: localhost
      API_PORT: 3000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  lint-typescript:
    name: eslint
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      API_ADDR: localhost
      API_PORT: 3000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: npm install
        working-directory: tournament-organiser-web
      - run: npm run lint-check:ci
        working-directory: tournament-organiser-web

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    env:
      API_ADDR: localhost
      API_PORT: 3000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            tournament-organiser-web/node_modules
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add clippy
      
      # setup
      - run: sudo apt-get update
      # https://dioxuslabs.com/docs/0.3/guide/en/getting_started/desktop.html#linux
      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
      - run: mkdir totsugeki-native-app/resources
      - run: touch totsugeki-native-app/resources/tailwind.css
      - run: mkdir web/resources
      - run: touch web/resources/tailwind.css

      - run: cargo clippy -- -D warnings

  tournament-organiser-cypress-tests:
    name: tournament organiser cypress tests
    # rust, node and npm are installed https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#rust-tools
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            tournament-organiser-web/node_modules
            tournament-organiser-web/dist
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: cypress-io/github-action@v5
        with:
          working-directory: tournament-organiser-web
          install: true
          build: npm run build:ci
          start: cargo run --package tournament-organiser-api --release
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 30
          browser: chrome
