on: [pull_request]

# NOTE avoid running on draft PR branches withi https://stackoverflow.com/questions/68349031/only-run-actions-on-non-draft-pull-request

name: Fuzzing

defaults:
  run:
    working-directory: ./totsugeki/fuzz

# cargo install fails if already installed. Then just exit with true
# TODO exit with 0 if already exit instead of ignoring all errors

jobs:
  bracket:
    name: bracket
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly || true
      - run: cargo +nightly install cargo-binutils || true # to call llvm-tools
      - run: cargo install cargo-fuzz || true
      - run: rustup toolchain install nightly --component llvm-tools-preview || true
      - run: cargo +nightly fuzz run bracket -- -max_total_time=60
  randomly_ordered_events:
    name: randomly ordered events
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly || true
      - run: cargo +nightly install cargo-binutils || true # to call llvm-tools
      - run: cargo install cargo-fuzz || true
      - run: rustup toolchain install nightly --component llvm-tools-preview || true
      - run: cargo +nightly fuzz run randomly_ordered_events -- -max_total_time=60
  big_brackets:
    name: big brackets
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly || true
      - run: cargo +nightly install cargo-binutils || true # to call llvm-tools
      - run: cargo install cargo-fuzz || true
      - run: rustup toolchain install nightly --component llvm-tools-preview || true
      - run: cargo +nightly fuzz run big_brackets -- -max_total_time=60
  big_brackets_de:
    name: big brackets double elimination
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly || true
      - run: cargo +nightly install cargo-binutils || true # to call llvm-tools
      - run: cargo install cargo-fuzz || true
      - run: rustup toolchain install nightly --component llvm-tools-preview || true
      - run: cargo +nightly fuzz run big_brackets_de -- -max_total_time=60
  very_big_brackets_de:
    name: very big brackets double elimination
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly || true
      - run: cargo +nightly install cargo-binutils || true # to call llvm-tools
      - run: cargo install cargo-fuzz || true
      - run: rustup toolchain install nightly --component llvm-tools-preview || true
      # did timeout once and exited with code 1
      # you could add -timeout_exitcode=0 but let's limit the imput size
      - run: cargo +nightly fuzz run very_big_brackets_de -- -max_total_time=60

