on: [pull_request]

name: Fuzzing

defaults:
  run:
    working-directory: ./totsugeki/fuzz

jobs:
  bracket:
    name: bracket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: cargo install cargo-fuzz
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: cargo +nightly fuzz run bracket -- -max_total_time=60
  randomly_ordered_events:
    name: randomly ordered events
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: cargo install cargo-fuzz
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: cargo +nightly fuzz run randomly_ordered_events -- -max_total_time=60
  big_brackets:
    name: big brackets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: cargo install cargo-fuzz
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: cargo +nightly fuzz run big_brackets -- -max_total_time=60
  big_brackets_de:
    name: big brackets double elimination
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: cargo install cargo-fuzz
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: cargo +nightly fuzz run big_brackets_de -- -max_total_time=60
  very_big_brackets_de:
    name: very big brackets double elimination
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
            corpus/
            coverage/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: cargo install cargo-fuzz
      - run: rustup toolchain install nightly --component llvm-tools-preview
      # did timeout once and exited with code 1
      # you could add -timeout_exitcode=0 but let's limit the imput size
      - run: cargo +nightly fuzz run very_big_brackets_de -- -max_total_time=60

