on: [pull_request]

name: Fuzzing

defaults:
  run:
    working-directory: ./totsugeki/fuzz

jobs:
  bracket:
    name: bracket
    runs-on: ubuntu-latest
    steps:
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: ls
      - run: ls totsugeki
      - run: ls ./totsugeki
      - run: ls ..
      - run: cargo +nightly fuzz run bracket -- -max_total_time_=60
  randomly_ordered_events:
    name: randomly ordered events
    runs-on: ubuntu-latest
    steps:
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: cargo +nightly fuzz run randomly_ordered_events -- -max_total_time_=60
  big_brackets:
    name: big brackets
    runs-on: ubuntu-latest
    steps:
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: cargo +nightly fuzz run big_brackets -- -max_total_time_=60
  big_brackets_de:
    name: big brackets double elimination
    runs-on: ubuntu-latest
    steps:
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: cargo +nightly fuzz run big_brackets_de -- -max_total_time_=60
  very_big_brackets_de:
    name: very big brackets double elimination
    runs-on: ubuntu-latest
    steps:
      - run: rustup toolchain install nightly
      - run: cargo +nightly install cargo-binutils # to call llvm-tools
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - run: cargo +nightly fuzz run very_big_brackets_de -- -max_total_time_=60

